/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as TemplatesBirthdayScrapbookIndexRouteImport } from './routes/templates.birthday-scrapbook.index'
import { Route as TemplatesBirthdayScrapbookBookRouteImport } from './routes/templates.birthday-scrapbook.book'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesBirthdayScrapbookIndexRoute =
  TemplatesBirthdayScrapbookIndexRouteImport.update({
    id: '/templates/birthday-scrapbook/',
    path: '/templates/birthday-scrapbook/',
    getParentRoute: () => rootRouteImport,
  } as any)
const TemplatesBirthdayScrapbookBookRoute =
  TemplatesBirthdayScrapbookBookRouteImport.update({
    id: '/templates/birthday-scrapbook/book',
    path: '/templates/birthday-scrapbook/book',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/templates/birthday-scrapbook/book': typeof TemplatesBirthdayScrapbookBookRoute
  '/templates/birthday-scrapbook/': typeof TemplatesBirthdayScrapbookIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin': typeof AdminIndexRoute
  '/templates/birthday-scrapbook/book': typeof TemplatesBirthdayScrapbookBookRoute
  '/templates/birthday-scrapbook': typeof TemplatesBirthdayScrapbookIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/templates/birthday-scrapbook/book': typeof TemplatesBirthdayScrapbookBookRoute
  '/templates/birthday-scrapbook/': typeof TemplatesBirthdayScrapbookIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/login'
    | '/admin/'
    | '/templates/birthday-scrapbook/book'
    | '/templates/birthday-scrapbook/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/login'
    | '/admin'
    | '/templates/birthday-scrapbook/book'
    | '/templates/birthday-scrapbook'
  id:
    | '__root__'
    | '/'
    | '/admin/login'
    | '/admin/'
    | '/templates/birthday-scrapbook/book'
    | '/templates/birthday-scrapbook/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
  TemplatesBirthdayScrapbookBookRoute: typeof TemplatesBirthdayScrapbookBookRoute
  TemplatesBirthdayScrapbookIndexRoute: typeof TemplatesBirthdayScrapbookIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/birthday-scrapbook/': {
      id: '/templates/birthday-scrapbook/'
      path: '/templates/birthday-scrapbook'
      fullPath: '/templates/birthday-scrapbook/'
      preLoaderRoute: typeof TemplatesBirthdayScrapbookIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/birthday-scrapbook/book': {
      id: '/templates/birthday-scrapbook/book'
      path: '/templates/birthday-scrapbook/book'
      fullPath: '/templates/birthday-scrapbook/book'
      preLoaderRoute: typeof TemplatesBirthdayScrapbookBookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
  TemplatesBirthdayScrapbookBookRoute: TemplatesBirthdayScrapbookBookRoute,
  TemplatesBirthdayScrapbookIndexRoute: TemplatesBirthdayScrapbookIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
